api_platform:
    title: AfterCoach API
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        persist_authorization: true